---
# This playbook deploys POD and Replication Controller on Kubernetes Cluster.

- name: create POD
  hosts: localhost
  tags:
     - createpod

  roles:
    - pod

- name: Create RC
  hosts: localhost
  tags:
     - createrc

  roles:
    - rc

- name: Deploy Wordpress
  hosts: localhost
  tags:
     - wordpress
  roles:
    - wordpress
