---
- name: pv claim creation
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/pv-claim.yml
    state: present
- name: Secrets Creation
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/wordpress-secrets.yml
    state: present
- name: Wordpress DB creation
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/wordpress-db.yml
    state: present
- name: DB Service
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/wordpress-db-service.yml
    state: present
- name: Wordpress FE Deployment
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/wordpress-web.yml
    state: present
- name: Wordpress FE Service
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: /var/lib/awx/projects/_9__k8s_ansible/roles/wordpress/files/wordpress-web-service.yml
    state: present
