---
- name: Redis Pod Deployment
  tags: 
     - createpod
  kubernetes:
    api_endpoint: "{{ api_endpoint }}"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    file_reference: files/redis.yml
    state: present
